---
name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  sync:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Sync labels with closing issues
        uses: williambdean/closing-labels@7a4384e0e725b80eee0142265d36c1332fda5f7a # v0.0.6
        with:
          exclude: "duplicate,help wanted,question"
        env:
          GH_TOKEN: ${{ github.token }}
